appName: argo-test
image:
  repository: nginx
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 80

resources:
  limits:
    memory: "512Mi"
    cpu: "500m"
  requests:
    memory: "256Mi"
    cpu: "250m"
